import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ variable: "--font-inter", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="preload"
          as="video"
          href="/videos/hero-1.mp4"
          type="video/mp4"
        />
        <link
          rel="preload"
          as="video"
          href="/videos/hero-2.mp4"
          type="video/mp4"
        />
        <link
          rel="preload"
          as="video"
          href="/videos/hero-3.mp4"
          type="video/mp4"
        />
        <link
          rel="preload"
          as="video"
          href="/videos/hero-4.mp4"
          type="video/mp4"
        />
      </head>
      <body className={`${inter.variable} antialiased scroll-smooth`}>
        {children}
      </body>
    </html>
  );
}
