name: Auto merge PR

on:
  repository_dispatch:
    types: [ "merge-pr" ]

jobs:
  merge_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Get PR number
        id: getpr
        run: |
          echo "PR number: ${{ github.event.client_payload.pr_number }}"
          echo "pr=${{ github.event.client_payload.pr_number }}" >> $GITHUB_ENV

      - name: Check for automerge label
        id: check_label
        run: |
          labels=$(gh pr view $pr --json labels -q '.labels[].name')
          echo "Labels: $labels"
          if echo "$labels" | grep -qw "automerge"; then
            echo "label_found=true" >> $GITHUB_OUTPUT
            echo "automerge label found"
          else
            echo "label_found=false" >> $GITHUB_OUTPUT
            echo "automerge label missing — skipping merge"
          fi
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Merge PR
        if: steps.check_label.outputs.label_found == 'true'
        uses: pascalgn/automerge-action@v0.16.4
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        env:
          MERGE_LABELS: automerge
          MERGE_METHOD: merge
          MERGE_DELETE_BRANCH: false
          MERGE_COMMIT_MESSAGE: pull-request-title
