name: Auto merge PR

on:
  repository_dispatch:
    types:
      - "merge-pr"

jobs:
  merge_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Get PR number
        run: echo "PR = ${{ github.event.client_payload.pr_number }}"

      - name: Check label on PR
        id: chk
        run: |
          pr=${{ github.event.client_payload.pr_number }}
          labels=$(gh pr view $pr --json labels -q '.labels[].name')
          echo "labels = $labels"
          if ! echo "$labels" | grep -w "automerge"; then
            echo "Label automerge missing — skipping" 
            exit 1
          fi
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Merge PR
        if: success()  
        uses: pascalgn/automerge-action@v0.16.4
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        env:
          MERGE_LABELS: automerge
          MERGE_METHOD: merge
